# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActorComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisposableComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='GradesComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopularityComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_actors', models.IntegerField(default=4)),
                ('actions_per_turn', models.IntegerField(default=2)),
                ('auto_create_ai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackableComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurnComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actions_left', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisibilityComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Ruleset'),
        ),
        migrations.AddField(
            model_name='entity',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='sim.Game'),
        ),
        migrations.AddField(
            model_name='disposablecomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity'),
        ),
        migrations.AddField(
            model_name='costcomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity'),
        ),
        migrations.AddField(
            model_name='actorcomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity'),
        ),
        migrations.AddField(
            model_name='actorcomponent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actioncomponent',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Entity'),
        ),
    ]
