# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_actorcomponent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='sim.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='auto_create_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='total_actors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
