# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20170401_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorcomponent',
            name='seat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
