# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_turncomponent_expended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turncomponent',
            name='expended',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
