# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_actorcomponent_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomponent',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
