# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_ruleset_rounds_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='turncomponent',
            name='round_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
