# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_turncomponent_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turncomponent',
            name='expended',
            field=models.DateTimeField(null=True),
        ),
    ]
