requestor = StudentApi.get_requestor()
adjacent_students = StudentApi.get_adjacent_students(requestor)
adjacent_students_count = len(adjacent_students)
StudentApi.add_popularity(requestor, adjacent_students_count)
StudentApi.add_trouble(requestor, 3)