requestor = ActorApi.get_requestor()
adjacent_students = StudentApi.get_adjacent_students(requestor.student)
adjacent_students_count = len(adjacent_students)
ActorApi.add_popularity(requestor, adjacent_students_count)
ActorApi.add_trouble(requestor, 3)
