requestor = ActorApi.get_requestor()
eligible_actors = ActorApi.get_adjacent_actors(requestor)
selected_actor = PromptApi.prompt_actor_choice(eligible_actors, "Target Actor")
ActorApi.add_popularity(selected_actor, -6)
ActorApi.add_trouble(requestor, 2)