requestor = ActorApi.get_requestor()
eligible_actors = ActorApi.get_all_but_requestor()
selected_actor = PromptApi.prompt_actor_choice(eligible_actors, "Target Actor")
ActorApi.add_trouble(selected_actor, 3)
ActorApi.add_popularity(requestor, -4)
ActorApi.add_trouble(requestor, -1)
