# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:27
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grades', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('is_sift', models.BooleanField()),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardTargetOperationSet',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('execution_order', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='card_target_operation_sets', to='game.Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('play_phase_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('target_field', models.CharField(max_length=255)),
                ('eligible_content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationSet',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhaseType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_automatic', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_limit', models.IntegerField(null=True)),
                ('requires_type',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='game.Pile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PileCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Card')),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Pile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('game',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField(null=True)),
                ('game',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('backstory', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('sift', models.TextField()),
                ('target_content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.DateTimeField(null=True)),
                ('actor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.Actor')),
                ('phase',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.Phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.StageType'),
        ),
        migrations.AddField(
            model_name='phasetype',
            name='stage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.StageType'),
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.PhaseType'),
        ),
        migrations.AddField(
            model_name='phase',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases',
                                    to='game.Stage'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='operation_sets',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='game.OperationSet'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Operator'),
        ),
        migrations.AddField(
            model_name='game',
            name='action_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='game',
            name='afterschool_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='game',
            name='discipline_card_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='cardtargetoperationset',
            name='operation_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='game.OperationSet'),
        ),
        migrations.AddField(
            model_name='cardtargetoperationset',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Target'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='piles',
            field=models.ManyToManyField(related_name='cards', through='game.PileCard', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='argument',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments',
                                    to='game.Instruction'),
        ),
        migrations.AddField(
            model_name='actor',
            name='action_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='actor',
            name='afterschool_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='actor',
            name='discard_pile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Pile'),
        ),
        migrations.AddField(
            model_name='actor',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='game.Game'),
        ),
        migrations.AddField(
            model_name='actor',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor',
                                       to='game.Seat'),
        ),
        migrations.AddField(
            model_name='actor',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='game.StudentInfo'),
        ),
        migrations.AddField(
            model_name='actor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='player_actors', to=settings.AUTH_USER_MODEL),
        ),
    ]
