# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationargument',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='game.Operation'),
            preserve_default=False,
        ),
    ]
