# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170408_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='argument',
        ),
        migrations.AddField(
            model_name='operation',
            name='arguments',
            field=models.ManyToManyField(related_name='operations', to='game.Argument'),
        ),
    ]
