# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170406_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTargetEffectSet',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectSet',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('sift', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='targeting_sift',
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='game.EffectSet'),
        ),
        migrations.AddField(
            model_name='cardtargeteffectset',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Card'),
        ),
        migrations.AddField(
            model_name='cardtargeteffectset',
            name='effect_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Card'),
        ),
        migrations.AddField(
            model_name='cardtargeteffectset',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Target'),
        ),
    ]
