# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_operationargument_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Operator'),
        ),
    ]
