# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170406_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effect_set',
        ),
        migrations.AddField(
            model_name='effect',
            name='effect_sets',
            field=models.ManyToManyField(related_name='effects', to='game.EffectSet'),
        ),
    ]
