# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0003_remove_mutationeffect_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutationeffect',
            name='name',
        ),
        migrations.AlterField(
            model_name='mutationeffect',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
