# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170408_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
