# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170427_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTag',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='action_card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='actor_action',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='afterschool_card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='afterschool_card_cost',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='automatic_card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='automatic_effect',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='card_cost',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='discipline_card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='on_draw',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='permanent',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='phase_bound',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='played_card',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='proximate_effect',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='source_actor_id',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='stage_bound',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='status_effect',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='system',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='target_actor_id',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='torment',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='trouble',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='turn_bound',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='until_removed',
        ),
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='use_bound',
        ),
        migrations.AddField(
            model_name='mutationtemplate',
            name='tags',
            field=models.ManyToManyField(to='game.OperationTag'),
        ),
    ]
