# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_auto_20170408_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='trouble',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
