# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170406_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtargeteffectset',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_target_effect_sets', to='game.Card'),
        ),
    ]
