# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0006_auto_20170427_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationtemplate',
            name='tags2',
            field=models.CharField(choices=[('actor_action', 'Actor Action'), ('card', 'Card')], default='actor_action',
                                   max_length=255),
            preserve_default=False,
        ),
    ]
