# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0007_actor_torment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtargetoperationset',
            name='execution_order',
            field=models.IntegerField(default=0),
        ),
    ]
