# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:20
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_mutationtemplate_tags2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PlayedCard', 'played_card'), ('DisciplineCard', 'discipline_card'), ('System', 'system'), ('UntilRemoved', 'until_removed'), ('AfterSchoolCardCost', 'afterschool_card_cost'), ('AutomaticCard', 'automatic_card'), ('Trouble', 'trouble'), ('TurnBound', 'turn_bound'), ('UseBound', 'use_bound'), ('Torment', 'torment'), ('PhaseBound', 'phase_bound'), ('AfterSchoolCard', 'afterschool_card'), ('CardCost', 'card_cost'), ('Card', 'card'), ('OnDraw', 'on_draw'), ('Popularity', 'popularity'), ('ActorAction', 'actor_action'), ('StatusEffect', 'status_effect'), ('ActionCard', 'action_card'), ('Grades', 'grades'), ('Permanent', 'permanent'), ('StageBound', 'stage_bound'), ('ProximateEffect', 'proximate_effect'), ('AutomaticEffect', 'automatic_effect')], max_length=269),
        ),
    ]
