# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0007_auto_20170406_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='effect',
            name='eligible_content_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='target_content_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
