# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:21
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0008_auto_20170428_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags2',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('on_draw', 'OnDraw'), ('trouble', 'Trouble'), ('popularity', 'Popularity'), ('card', 'Card'),
                         ('until_removed', 'UntilRemoved'), ('phase_bound', 'PhaseBound'), ('torment', 'Torment'),
                         ('afterschool_card', 'AfterSchoolCard'), ('turn_bound', 'TurnBound'),
                         ('proximate_effect', 'ProximateEffect'), ('grades', 'Grades'),
                         ('status_effect', 'StatusEffect'), ('afterschool_card_cost', 'AfterSchoolCardCost'),
                         ('permanent', 'Permanent'), ('played_card', 'PlayedCard'), ('stage_bound', 'StageBound'),
                         ('automatic_effect', 'AutomaticEffect'), ('automatic_card', 'AutomaticCard'),
                         ('actor_action', 'ActorAction'), ('discipline_card', 'DisciplineCard'), ('system', 'System'),
                         ('card_cost', 'CardCost'), ('use_bound', 'UseBound'), ('action_card', 'ActionCard')],
                max_length=287),
        ),
    ]
