# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170407_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
