# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect_sets',
            field=models.ManyToManyField(related_name='effects', to='game.EffectSet'),
        ),
    ]
