# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170412_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
