# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:21
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0010_auto_20170428_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='tags2',
        ),
        migrations.AddField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('card', 'Card'), ('use_bound', 'UseBound'), ('afterschool_card', 'AfterSchoolCard'),
                         ('proximate_effect', 'ProximateEffect'), ('on_draw', 'OnDraw'),
                         ('actor_action', 'ActorAction'), ('action_card', 'ActionCard'), ('trouble', 'Trouble'),
                         ('automatic_card', 'AutomaticCard'), ('phase_bound', 'PhaseBound'),
                         ('status_effect', 'StatusEffect'), ('card_cost', 'CardCost'), ('torment', 'Torment'),
                         ('permanent', 'Permanent'), ('stage_bound', 'StageBound'), ('system', 'System'),
                         ('grades', 'Grades'), ('turn_bound', 'TurnBound'), ('played_card', 'PlayedCard'),
                         ('popularity', 'Popularity'), ('automatic_effect', 'AutomaticEffect'),
                         ('afterschool_card_cost', 'AfterSchoolCardCost'), ('until_removed', 'UntilRemoved'),
                         ('discipline_card', 'DisciplineCard')], default='Card', max_length=287),
            preserve_default=False,
        ),
    ]
