# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170428_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('card', 'Card'), ('discipline_card', 'DisciplineCard'), ('on_draw', 'OnDraw'), ('card_cost', 'CardCost'), ('popularity', 'Popularity'), ('system', 'System'), ('until_removed', 'UntilRemoved'), ('torment', 'Torment'), ('automatic_card', 'AutomaticCard'), ('actor_action', 'ActorAction'), ('afterschool_card_cost', 'AfterSchoolCardCost'), ('permanent', 'Permanent'), ('automatic_effect', 'AutomaticEffect'), ('stage_bound', 'StageBound'), ('phase_bound', 'PhaseBound'), ('proximate_effect', 'ProximateEffect'), ('action_card', 'ActionCard'), ('use_bound', 'UseBound'), ('status_effect', 'StatusEffect'), ('trouble', 'Trouble'), ('afterschool_card', 'AfterSchoolCard'), ('turn_bound', 'TurnBound'), ('played_card', 'PlayedCard'), ('grades', 'Grades')], max_length=287),
        ),
    ]
