# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170412_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtargetoperationset',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
