# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:27
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0013_auto_20170428_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='description',
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('on_draw', 'OnDraw'), ('trouble', 'Trouble'), ('card', 'Card'), ('permanent', 'Permanent'),
                         ('proximate_effect', 'ProximateEffect'), ('status_effect', 'StatusEffect'),
                         ('card_cost', 'CardCost'), ('phase_bound', 'PhaseBound'), ('popularity', 'Popularity'),
                         ('use_bound', 'UseBound'), ('afterschool_card_cost', 'AfterSchoolCardCost'),
                         ('stage_bound', 'StageBound'), ('torment', 'Torment'), ('automatic_effect', 'AutomaticEffect'),
                         ('action_card', 'ActionCard'), ('discipline_card', 'DisciplineCard'),
                         ('until_removed', 'UntilRemoved'), ('system', 'System'), ('automatic_card', 'AutomaticCard'),
                         ('played_card', 'PlayedCard'), ('grades', 'Grades'), ('actor_action', 'ActorAction'),
                         ('afterschool_card', 'AfterSchoolCard'), ('turn_bound', 'TurnBound')], max_length=287),
        ),
    ]
