# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170412_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='trouble_cost',
            field=models.IntegerField(default=0),
        ),
    ]
