# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_card_trouble_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='script',
            field=models.TextField(default=''),
        ),
    ]
