# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 23:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20170428_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CardCost', 'Card Cost'), ('Card', 'Card'), ('AutomaticCard', 'Automatic Card'), ('ActorAction', 'Actor Action'), ('Trouble', 'Trouble'), ('StageBound', 'Stage Bound'), ('PhaseBound', 'Phase Bound'), ('OnDraw', 'On Draw'), ('AfterSchoolCardCost', 'After School Card Cost'), ('Permanent', 'Permanent'), ('AfterSchoolCard', 'After School Card'), ('System', 'System'), ('DisciplineCard', 'Discipline Card'), ('Popularity', 'Popularity'), ('StatusEffect', 'Status Effect'), ('ActionCard', 'Action Card'), ('TurnBound', 'Turn Bound'), ('ProximateEffect', 'Proximate Effect'), ('AutomaticEffect', 'Automatic Effect'), ('Torment', 'Torment'), ('UntilRemoved', 'Until Removed'), ('UseBound', 'Use Bound'), ('PlayedCard', 'Played Card'), ('Grades', 'Grades')], max_length=269),
        ),
    ]
