# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_card_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilecard',
            name='pile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pile_cards', to='game.Pile'),
        ),
    ]
