# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0016_auto_20170414_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
