# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 23:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20170428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Card', 'Card'), ('OnDraw', 'On Draw'), ('UntilRemoved', 'Until Removed'), ('DisciplineCard', 'Discipline Card'), ('PhaseBound', 'Phase Bound'), ('StageBound', 'Stage Bound'), ('StatusEffect', 'Status Effect'), ('ActorAction', 'Actor Action'), ('Popularity', 'Popularity'), ('System', 'System'), ('ActionCard', 'Action Card'), ('UseBound', 'Use Bound'), ('AfterSchoolCard', 'After School Card'), ('AutomaticEffect', 'Automatic Effect'), ('CardCost', 'Card Cost'), ('Trouble', 'Trouble'), ('Grades', 'Grades'), ('TurnBound', 'Turn Bound'), ('PlayedCard', 'Played Card'), ('ProximateEffect', 'Proximate Effect'), ('AutomaticCard', 'Automatic Card'), ('Torment', 'Torment'), ('Permanent', 'Permanent'), ('AfterSchoolCardCost', 'After School Card Cost')], max_length=269),
        ),
    ]
