# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 01:27
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0018_auto_20170428_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationtemplate',
            name='uses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('StatusEffect', 'Status Effect'), ('StageBound', 'Stage Bound'),
                         ('ActionCard', 'Action Card'), ('AutomaticCard', 'Automatic Card'),
                         ('DisciplineCard', 'Discipline Card'), ('PlayedCard', 'Played Card'),
                         ('Popularity', 'Popularity'), ('UseBound', 'Use Bound'),
                         ('AfterSchoolCardCost', 'After School Card Cost'), ('PhaseBound', 'Phase Bound'),
                         ('AfterSchoolCard', 'After School Card'), ('Card', 'Card'),
                         ('AutomaticEffect', 'Automatic Effect'), ('System', 'System'), ('Trouble', 'Trouble'),
                         ('CardCost', 'Card Cost'), ('TurnBound', 'Turn Bound'),
                         ('ProximateEffect', 'Proximate Effect'), ('OnDraw', 'On Draw'),
                         ('ActionCardCost', 'Action Card Cost'), ('UntilRemoved', 'Until Removed'),
                         ('ActorAction', 'Actor Action'), ('Torment', 'Torment'), ('Grades', 'Grades'),
                         ('Permanent', 'Permanent')], max_length=284),
        ),
    ]
