# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20170414_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtargetoperationset',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardtargetoperationset',
            name='operation_set',
        ),
        migrations.RemoveField(
            model_name='cardtargetoperationset',
            name='target',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='eligible_content_type',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_set',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_content_type',
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
        migrations.DeleteModel(
            name='CardTargetOperationSet',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='OperationSet',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
