# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20170428_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('UntilRemoved', 'UntilRemoved'), ('Turn Bound', 'Turn Bound'), ('Stage Bound', 'Stage Bound'), ('Action Bound', 'Action Bound'), ('Phase Bound', 'Phase Bound')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Permanent', 'Permanent'), ('After School Card', 'After School Card'), ('Automatic Card', 'Automatic Card'), ('On Draw', 'On Draw'), ('Played Card', 'Played Card'), ('Torment', 'Torment'), ('Action Card', 'Action Card'), ('Automatic Effect', 'Automatic Effect'), ('Grades', 'Grades'), ('Phase Bound', 'Phase Bound'), ('System', 'System'), ('Popularity', 'Popularity'), ('After School Card Cost', 'After School Card Cost'), ('Card', 'Card'), ('Proximate Effect', 'Proximate Effect'), ('Turn Bound', 'Turn Bound'), ('Stage Bound', 'Stage Bound'), ('Discipline Card', 'Discipline Card'), ('Until Removed', 'Until Removed'), ('Action Card Cost', 'Action Card Cost'), ('Actor Action', 'Actor Action'), ('Status Effect', 'Status Effect'), ('Card Cost', 'Card Cost'), ('Trouble', 'Trouble'), ('Use Bound', 'Use Bound')], max_length=306),
        ),
        migrations.DeleteModel(
            name='MutationExpiryCriteria',
        ),
    ]
