# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20170415_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='fear_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='fear_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='perk_description',
            field=models.TextField(),
        ),
    ]
