# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20170429_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=models.CharField(choices=[('Phase Bound', 'Phase Bound'), ('Turn Bound', 'Turn Bound'), ('Action Bound', 'Action Bound'), ('Stage Bound', 'Stage Bound'), ('Permanent', 'Permanent'), ('Until Removed', 'Until Removed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Automatic Effect', 'Automatic Effect'), ('Status Effect', 'Status Effect'), ('Automatic Card', 'Automatic Card'), ('Action Card Cost', 'Action Card Cost'), ('Torment', 'Torment'), ('Permanent', 'Permanent'), ('Use Bound', 'Use Bound'), ('Popularity', 'Popularity'), ('Action Card', 'Action Card'), ('After School Card', 'After School Card'), ('System', 'System'), ('Card Cost', 'Card Cost'), ('Phase Bound', 'Phase Bound'), ('After School Card Cost', 'After School Card Cost'), ('Played Card', 'Played Card'), ('On Draw', 'On Draw'), ('Turn Bound', 'Turn Bound'), ('Stage Bound', 'Stage Bound'), ('Discipline Card', 'Discipline Card'), ('Proximate Effect', 'Proximate Effect'), ('Actor Action', 'Actor Action'), ('Trouble', 'Trouble'), ('Grades', 'Grades'), ('Card', 'Card'), ('Until Removed', 'Until Removed')], max_length=306),
        ),
    ]
