# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 10:36
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0021_auto_20170429_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=models.CharField(choices=[('Until Removed', 'Until Removed'), ('Turn Bound', 'Turn Bound'),
                                            ('Phase Bound', 'Phase Bound'), ('Permanent', 'Permanent'),
                                            ('Action Bound', 'Action Bound'), ('Stage Bound', 'Stage Bound'),
                                            ('Use Bound', 'Use Bound')], default='Permanent', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('Action Card Cost', 'Action Card Cost'), ('Action Card', 'Action Card'),
                         ('Until Removed', 'Until Removed'), ('Phase Bound', 'Phase Bound'), ('Grades', 'Grades'),
                         ('After School Card', 'After School Card'), ('Popularity', 'Popularity'), ('Card', 'Card'),
                         ('Stage Bound', 'Stage Bound'), ('Automatic Effect', 'Automatic Effect'),
                         ('Discipline Card', 'Discipline Card'), ('On Draw', 'On Draw'), ('Played Card', 'Played Card'),
                         ('Permanent', 'Permanent'), ('Use Bound', 'Use Bound'), ('Automatic Card', 'Automatic Card'),
                         ('Proximate Effect', 'Proximate Effect'), ('Actor Action', 'Actor Action'),
                         ('Turn Bound', 'Turn Bound'), ('Card Cost', 'Card Cost'), ('Trouble', 'Trouble'),
                         ('Status Effect', 'Status Effect'), ('System', 'System'),
                         ('After School Card Cost', 'After School Card Cost'), ('Torment', 'Torment')], max_length=306),
        ),
    ]
