# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:14
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0021_auto_20170415_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='actor',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='student_info',
        ),
        migrations.AddField(
            model_name='student',
            name='actor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student',
                                       to='game.Actor'),
        ),
        migrations.AddField(
            model_name='student',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student',
                                       to='game.Seat'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='game.StudentInfo'),
        ),
    ]
