# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 10:40
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0022_auto_20170429_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutationtemplate',
            name='uses',
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=models.CharField(
                choices=[('Turn Bound', 'Turn Bound'), ('Use Bound', 'Use Bound'), ('Permanent', 'Permanent'),
                         ('Phase Bound', 'Phase Bound'), ('Stage Bound', 'Stage Bound'),
                         ('Action Bound', 'Action Bound'), ('Until Removed', 'Until Removed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('After School Card', 'After School Card'), ('Turn Bound', 'Turn Bound'),
                         ('On Draw', 'On Draw'), ('Permanent', 'Permanent'), ('Popularity', 'Popularity'),
                         ('Stage Bound', 'Stage Bound'), ('Card', 'Card'), ('Proximate Effect', 'Proximate Effect'),
                         ('Until Removed', 'Until Removed'), ('Played Card', 'Played Card'),
                         ('Automatic Effect', 'Automatic Effect'), ('Trouble', 'Trouble'), ('Card Cost', 'Card Cost'),
                         ('Use Bound', 'Use Bound'), ('Action Card', 'Action Card'), ('Grades', 'Grades'),
                         ('System', 'System'), ('Action Card Cost', 'Action Card Cost'), ('Phase Bound', 'Phase Bound'),
                         ('Discipline Card', 'Discipline Card'), ('After School Card Cost', 'After School Card Cost'),
                         ('Torment', 'Torment'), ('Actor Action', 'Actor Action'), ('Automatic Card', 'Automatic Card'),
                         ('Status Effect', 'Status Effect')], max_length=306),
        ),
    ]
