# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 11:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20170429_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Stage Bound', 'Stage Bound'), ('Use Bound', 'Use Bound'), ('Permanent', 'Permanent'), ('Action Bound', 'Action Bound'), ('Turn Bound', 'Turn Bound'), ('Until Removed', 'Until Removed'), ('Phase Bound', 'Phase Bound')], max_length=81),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Trouble', 'Trouble'), ('Grades', 'Grades'), ('Automatic Effect', 'Automatic Effect'), ('Stage Bound', 'Stage Bound'), ('Use Bound', 'Use Bound'), ('Proximate Effect', 'Proximate Effect'), ('System', 'System'), ('After School Card', 'After School Card'), ('Torment', 'Torment'), ('Phase Bound', 'Phase Bound'), ('Card', 'Card'), ('Action Card', 'Action Card'), ('Action Card Cost', 'Action Card Cost'), ('Automatic Card', 'Automatic Card'), ('Status Effect', 'Status Effect'), ('Actor Action', 'Actor Action'), ('After School Card Cost', 'After School Card Cost'), ('On Draw', 'On Draw'), ('Card Cost', 'Card Cost'), ('Played Card', 'Played Card'), ('Popularity', 'Popularity'), ('Discipline Card', 'Discipline Card'), ('Turn Bound', 'Turn Bound'), ('Until Removed', 'Until Removed'), ('Permanent', 'Permanent')], max_length=306),
        ),
    ]
