# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 19:23
from __future__ import unicode_literals

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0024_auto_20170429_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('Action Bound', 'Action Bound'), ('Until Removed', 'Until Removed'),
                         ('Use Bound', 'Use Bound'), ('Permanent', 'Permanent'), ('Turn Bound', 'Turn Bound'),
                         ('Stage Bound', 'Stage Bound'), ('Phase Bound', 'Phase Bound')], max_length=81),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('Until Removed', 'Until Removed'), ('Trouble', 'Trouble'),
                         ('After School Card', 'After School Card'), ('System', 'System'),
                         ('Proximate Effect', 'Proximate Effect'), ('Card Cost', 'Card Cost'),
                         ('Action Card Cost', 'Action Card Cost'), ('Permanent', 'Permanent'),
                         ('Action Card', 'Action Card'), ('Automatic Effect', 'Automatic Effect'),
                         ('Actor Action', 'Actor Action'), ('On Draw', 'On Draw'), ('Played Card', 'Played Card'),
                         ('Card', 'Card'), ('Popularity', 'Popularity'), ('Status Effect', 'Status Effect'),
                         ('Trouble per Turn', 'Trouble per Turn'), ('Use Bound', 'Use Bound'),
                         ('Grades per Turn', 'Grades per Turn'), ('After School Card Cost', 'After School Card Cost'),
                         ('Discipline Card', 'Discipline Card'), ('Turn Bound', 'Turn Bound'), ('Torment', 'Torment'),
                         ('Stage Bound', 'Stage Bound'), ('Grades', 'Grades'), ('Automatic Card', 'Automatic Card'),
                         ('Phase Bound', 'Phase Bound')], max_length=339),
        ),
    ]
