# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20170429_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationtemplate',
            name='gameflow_binding',
            field=models.CharField(choices=[('Stage', 'Stage'), ('Game', 'Game'), ('Phase', 'Phase'), ('Turn', 'Turn')], default='Game', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutationtemplate',
            name='uses',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='expiry_criteria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Use Bound', 'Use Bound'), ('Until Removed', 'Until Removed'), ('Action Bound', 'Action Bound'), ('Turn Bound', 'Turn Bound'), ('Permanent', 'Permanent'), ('Phase Bound', 'Phase Bound'), ('Stage Bound', 'Stage Bound')], max_length=81),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Draw After School Card', 'Draw After School Card'), ('Action Card', 'Action Card'), ('Turn Bound', 'Turn Bound'), ('Trouble per Turn', 'Trouble per Turn'), ('Proximate Effect', 'Proximate Effect'), ('Permanent', 'Permanent'), ('Seat', 'Seat'), ('Draw Action Card', 'Draw Action Card'), ('Card', 'Card'), ('Use Bound', 'Use Bound'), ('Draw', 'Draw'), ('After School Card', 'After School Card'), ('Trouble', 'Trouble'), ('Played Card', 'Played Card'), ('Popularity', 'Popularity'), ('Torment', 'Torment'), ('Discipline Card', 'Discipline Card'), ('Automatic Card', 'Automatic Card'), ('System', 'System'), ('Phase Bound', 'Phase Bound'), ('Actor Action', 'Actor Action'), ('Stage Bound', 'Stage Bound'), ('Automatic Effect', 'Automatic Effect'), ('Grades per Turn', 'Grades per Turn'), ('Grades', 'Grades'), ('Card Cost', 'Card Cost'), ('Action Card Cost', 'Action Card Cost'), ('Until Removed', 'Until Removed'), ('Status Effect', 'Status Effect'), ('After School Card Cost', 'After School Card Cost')], max_length=381),
        ),
    ]
