# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20170505_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='gameflow_binding',
            field=models.CharField(choices=[('Next Classtime Phase', 'Next Classtime Phase'), ('Game', 'Game'), ('Turn', 'Turn'), ('Phase', 'Phase'), ('Stage', 'Stage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Draw After School Card', 'Draw After School Card'), ('Grades', 'Grades'), ('Permanent', 'Permanent'), ('Seat', 'Seat'), ('Card Cost', 'Card Cost'), ('Proximate Effect', 'Proximate Effect'), ('After School Card', 'After School Card'), ('Trouble per Turn', 'Trouble per Turn'), ('Played Card', 'Played Card'), ('Until Removed', 'Until Removed'), ('Popularity', 'Popularity'), ('Use Bound', 'Use Bound'), ('Actor Action', 'Actor Action'), ('Discipline Card', 'Discipline Card'), ('Automatic Effect', 'Automatic Effect'), ('Card', 'Card'), ('Turn Bound', 'Turn Bound'), ('Phase Bound', 'Phase Bound'), ('Grades per Turn', 'Grades per Turn'), ('Draw', 'Draw'), ('Stage Bound', 'Stage Bound'), ('Status Effect', 'Status Effect'), ('Automatic Card', 'Automatic Card'), ('After School Card Cost', 'After School Card Cost'), ('Draw Action Card', 'Draw Action Card'), ('System', 'System'), ('Torment', 'Torment'), ('Trouble', 'Trouble'), ('Action Card', 'Action Card'), ('Action Card Cost', 'Action Card Cost')], max_length=381),
        ),
    ]
