# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20170505_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutationtemplate',
            name='gameflow_binding',
            field=models.CharField(choices=[('Next Dismissal Phase', 'Next Dismissal Phase'), ('Turn', 'Turn'), ('Next After School Phase', 'Next After School Phase'), ('Next Score Phase', 'Next Score Phase'), ('Game', 'Game'), ('Next Classtime Phase', 'Next Classtime Phase'), ('Next Choose Seats Phase', 'Next Choose Seats Phase'), ('Next Accumulation Phase', 'Next Accumulation Phase'), ('Phase', 'Phase'), ('Stage', 'Stage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mutationtemplate',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Phase Bound', 'Phase Bound'), ('Popularity', 'Popularity'), ('Grades per Turn', 'Grades per Turn'), ('Status Effect', 'Status Effect'), ('Permanent', 'Permanent'), ('Seat', 'Seat'), ('Actor Action', 'Actor Action'), ('Card', 'Card'), ('Action Card', 'Action Card'), ('Torment', 'Torment'), ('Played Card', 'Played Card'), ('System', 'System'), ('After School Card Cost', 'After School Card Cost'), ('Trouble per Turn', 'Trouble per Turn'), ('Automatic Effect', 'Automatic Effect'), ('Use Bound', 'Use Bound'), ('Draw Action Card', 'Draw Action Card'), ('After School Card', 'After School Card'), ('Automatic Card', 'Automatic Card'), ('Card Cost', 'Card Cost'), ('Action Card Cost', 'Action Card Cost'), ('Stage Bound', 'Stage Bound'), ('Grades', 'Grades'), ('Draw After School Card', 'Draw After School Card'), ('Draw', 'Draw'), ('Until Removed', 'Until Removed'), ('Trouble', 'Trouble'), ('Discipline Card', 'Discipline Card'), ('Proximate Effect', 'Proximate Effect'), ('Turn Bound', 'Turn Bound')], max_length=381),
        ),
    ]
